env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: gz
    format_overrides:
    - goos: windows
      format: zip
    files:
    - none*
checksum:
  name_template: "checksums.txt"
